/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  safelist: ['text-pink-300', 'bg-pink-500/20', 'border-pink-500/30'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#38265a',
        'inverse-surface': '#e8dff5',
        'on-surface-variant': '#ccc3d8',
        'error': '#ffb4ab',
        'surface-tint': '#d2bbff',
        'tertiary-container': '#c7232b',
        'surface-container': '#221d2d',
        'secondary-container': '#4f3d72',
        'on-primary-container': '#ede0ff',
        'on-tertiary-container': '#ffdfdc',
        'surface-container-highest': '#373243',
        'outline': '#958da1',
        'surface-container-high': '#2c2738',
        'on-surface': '#e8dff5',
        'outline-variant': '#4a4455',
        'tertiary': '#ffb3ae',
        'on-background': '#e8dff5',
        'background': '#151120',
        'surface-container-low': '#1d1929',
        'surface-variant': '#373243',
        'on-secondary-container': '#c1abe8',
        'error-container': '#93000a',
        'surface-container-lowest': '#100c1b',
        'inverse-primary': '#732ee4',
        'on-primary': '#3f008e',
        'primary': '#d2bbff',
        'inverse-on-surface': '#332e3f',
        'surface': '#151120',
        'surface-bright': '#3c3748',
        'secondary': '#d2bcfa',
        'surface-dim': '#151120',
        'primary-container': '#7c3aed',
        'secondary-fixed': '#ebddff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        display: ['Hanken Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        price: ['Geist', 'monospace'],
      },
      maxWidth: {
        'container': '1280px',
      },
      keyframes: {
        'slide-in-right': {
          '0%':   { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-out-right': {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'fade-in': {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%':   { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'pop-in': {
          '0%':   { transform: 'scale(0.8)', opacity: '0' },
          '70%':  { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'badge-bump': {
          '0%, 100%': { transform: 'scale(1)' },
          '40%':      { transform: 'scale(1.4)' },
        },
        'spin-slow': {
          '0%':   { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'cart-bounce': {
          '0%':   { transform: 'scale(1)' },
          '30%':  { transform: 'scale(1.35) rotate(-8deg)' },
          '60%':  { transform: 'scale(0.92) rotate(4deg)' },
          '100%': { transform: 'scale(1) rotate(0deg)' },
        },
        'bell-shake': {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '20%':      { transform: 'rotate(15deg)' },
          '40%':      { transform: 'rotate(-12deg)' },
          '60%':      { transform: 'rotate(8deg)' },
          '80%':      { transform: 'rotate(-5deg)' },
        },
        'card-flash': {
          '0%':   { boxShadow: '0 0 0px rgba(210,187,255,0)' },
          '40%':  { boxShadow: '0 0 32px rgba(210,187,255,0.6)' },
          '100%': { boxShadow: '0 0 0px rgba(210,187,255,0)' },
        },
        'fab-pop': {
          '0%':   { transform: 'scale(0)', opacity: '0' },
          '70%':  { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-4px)' },
        },
        'slide-up': {
          '0%':   { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      animation: {
        'slide-in-right':  'slide-in-right 0.3s cubic-bezier(0.32,0.72,0,1)',
        'slide-out-right': 'slide-out-right 0.25s ease-in forwards',
        'fade-in':         'fade-in 0.2s ease-out',
        'fade-out':        'fade-out 0.2s ease-in forwards',
        'pop-in':          'pop-in 0.25s cubic-bezier(0.34,1.56,0.64,1)',
        'badge-bump':      'badge-bump 0.35s ease-out',
        'spin-slow':       'spin-slow 3s linear infinite',
        'cart-bounce':     'cart-bounce 0.5s cubic-bezier(0.34,1.56,0.64,1)',
        'bell-shake':      'bell-shake 0.6s ease-in-out',
        'card-flash':      'card-flash 0.5s ease-out',
        'fab-pop':         'fab-pop 0.4s cubic-bezier(0.34,1.56,0.64,1)',
        'float':           'float 3s ease-in-out infinite',
        'slide-up':        'slide-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
