/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#38265a',
        'inverse-surface': '#e8dff5',
        'on-surface-variant': '#ccc3d8',
        'error': '#ffb4ab',
        'surface-tint': '#d2bbff',
        'tertiary-container': '#c7232b',
        'surface-container': '#221d2d',
        'secondary-container': '#4f3d72',
        'on-primary-container': '#ede0ff',
        'on-tertiary-container': '#ffdfdc',
        'surface-container-highest': '#373243',
        'outline': '#958da1',
        'surface-container-high': '#2c2738',
        'on-surface': '#e8dff5',
        'outline-variant': '#4a4455',
        'tertiary': '#ffb3ae',
        'on-background': '#e8dff5',
        'background': '#151120',
        'surface-container-low': '#1d1929',
        'surface-variant': '#373243',
        'on-secondary-container': '#c1abe8',
        'error-container': '#93000a',
        'surface-container-lowest': '#100c1b',
        'inverse-primary': '#732ee4',
        'on-primary': '#3f008e',
        'primary': '#d2bbff',
        'inverse-on-surface': '#332e3f',
        'surface': '#151120',
        'surface-bright': '#3c3748',
        'secondary': '#d2bcfa',
        'surface-dim': '#151120',
        'primary-container': '#7c3aed',
        'secondary-fixed': '#ebddff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        display: ['Hanken Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        price: ['Geist', 'monospace'],
      },
      maxWidth: {
        'container': '1280px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
